version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - walletsite:walletsite
      - keydownloader:keydownloader
    volumes:
      - ./config/dispatcher:/config
  keydownloader:
    image: madnificent/jobwallet-keydownloader-service
    links:
      - db:database
      - walletsite:walletsite
    volumes:
      - "./data/wallets/:/fileshare/wallets/"
  walletsite:
    image: kyma/docker-nginx
    volumes:
      - ./data/walletsite/:/var/www
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources
    links:
      - db:database
    volumes:
      - ./config/resources:/config
