version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - walletsite:walletsite
      - keydownloader:keydownloader
    volumes:
      - ./config/dispatcher:/config
  keydownloader:
    image: madnificent/jobwallet-keydownloader-service
    links:
      - db:database
      - walletsite:walletsite
    volumes:
      - "./data/wallets/:/fileshare/wallets/"
  walletsite:
    image: kyma/docker-nginx
    volumes:
      - ./data/walletsite/:/var/www
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  delta:
    image: semtech/mu-delta-service:beta-0.9
    ports:
      - "9980:8890"
    volumes:
      - ./config/delta:/config
    environment:
      CONFIGFILE: "/config/config.properties"
      SUBSCRIBERSFILE: "/config/subscribers.json"
    links:
      - db:db
  importer:
    # image: importer
    image: semtech/mu-ruby-template:2.0.0-ruby2.3
    links:
      - db:database
    ports:
      - "4444:80"
    volumes:
      - ./uploads:/data/uploads
      - /home/langens-jonathan/projects/jobwallet/jobwallet-importer:/app
    environment:
      RACK_ENV: "development"
  uploader:
    image: uploader
    links:
      - delta:database
    ports:
      - "5555:80"
    volumes:
      - ./uploads:/data/uploads
    environment:
      FILE_SERVICE_BASE_URI: "http://example.com/files/"
      FILE_SERVICE_FILE_CLASS: "http://file-service.com/File"
      FILE_SERVICE_FILE_NAME: "http://file.com/filename"
      FILE_SERVICE_FILE_STATUS: "http://file.com/status"
